version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: task-market-db-container
    environment:
      MYSQL_ROOT_PASSWORD: team-gyat
      MYSQL_DATABASE: task-market-db
      MYSQL_USER: mqsql-user
      MYSQL_PASSWORD: mysql-password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
