"""Make requester_id nullable in Jobs table

Revision ID: 5564639c6282
Revises: 67c181d26ffa
Create Date: 2024-12-02 15:25:03.265609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5564639c6282'
down_revision = '67c181d26ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.alter_column(
            'requester_id',
            existing_type=sa.VARCHAR(length=100),
            nullable=True
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.alter_column(
            'requester_id',
            existing_type=sa.VARCHAR(length=100),
            nullable=False
        )